version: 0.0

os: linux

files:
  - source: /deploy/
    destination: /home/ubuntu
permission:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStop:
    - loaction: scripts/kill_process.sh
      timeout: 100
      runas: ubuntu
  ApplicationStart:
    - loaction: scripts/run_process.sh
      timeout: 3600
      runas: ubuntu
