pipeline {
  agent any
  tools {
    maven "M3"
    jdk "JDK11"
  }
  environment {
    AWS_CREDENTIAL_NAME = "awsEcrCredentials"
    AWS_ACCOUNT_ID = "257307634175"
    REGION = "ap-northeast-2"
    DOCKER_IMAGE_NAME = "aws14-spring-petclinic"
    DOCKER_TAG = "1.0"
    ECR_REPOSITORY = "${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com"
    ECR_DOCKER_IMAGE = "${ECR_REPOSITORY}/${DOCKER_IMAGE_NAME}"
    ECR_DOCKER_TAG = "${DOCKER_TAG}"
  }
   stages {
    stage ('Git fatch') {
      steps {
       echo 'Git fatch'
       git url: 'https://github.com/cowlsla/spring-petclinic.git',
         branch: 'main', credentialsId: 'gitCredential'
      }
    }
    stage ('Mvn Build') {
      steps {
        echo 'Mvn Build'
        sh 'mvn -Dmaven.test.failure.ignore=true clean package'
      }
    }
    stage ('Docker Image') {
      steps {
        echo 'Docker Image'
        dir("${env.WORKSPACE}") {
          sh 'docker build -t aws14-spring-petclinic:1.0 ./'
        }
      }
    }
    stage ('Image Push') {
      steps {
       echo 'Image Push' 
      }
    }
    stage ('Codedeploy') {
      steps {
       echo 'Codedeploy' 
      }
    }
  }
}
